# Generated by Django 3.1.4 on 2021-03-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateprep', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WeekMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuFri', to='plateprep.recipe')),
                ('Mon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuMon', to='plateprep.recipe')),
                ('Sat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuSat', to='plateprep.recipe')),
                ('Sun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuSun', to='plateprep.recipe')),
                ('Thu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuThu', to='plateprep.recipe')),
                ('Tue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuTue', to='plateprep.recipe')),
                ('Wed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MenuWed', to='plateprep.recipe')),
            ],
        ),
    ]
