# Generated by Django 3.1.4 on 2021-03-08 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateprep', '0006_auto_20210308_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weekmenu',
            name='Fri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuFri', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Mon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuMon', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Sat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuSat', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Sun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuSun', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Thu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuThu', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Tue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuTue', to='plateprep.recipe'),
        ),
        migrations.AlterField(
            model_name='weekmenu',
            name='Wed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MenuWed', to='plateprep.recipe'),
        ),
    ]
