# Generated by Django 3.1.4 on 2021-03-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plateprep', '0007_auto_20210308_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekmenu',
            name='MealType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menuType', to='plateprep.meal'),
        ),
        migrations.AddField(
            model_name='weekmenu',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userMenu', to=settings.AUTH_USER_MODEL),
        ),
    ]
