# Generated by Django 3.1.4 on 2021-03-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateprep', '0010_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
